- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    # Grab the `foreman_certname` value from each host in `all` group
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#selecting-values-from-arrays-or-hashtables
    - debug:
        var: groups['all'] | map('extract', hostvars, 'foreman_certname') | list
