# Tate DeVito
# 
# References: 
# https://stackoverflow.com/questions/59949438/compare-ansible-registered-variables-for-multiple-hosts

- name: Discover if two host records are different based, and take action accordingly
  hosts: 
    - localhost
    - ansible_rhel
  gather_facts: no

  tasks:
    - name: Record localhost hostname as a variable 
      debug:
        var: hostvars[inventory_hostname]
      register: hostvars_localhost
      delegate_to: localhost

    - name: Record ansible_rhel hostname as a variable 
      debug:
        var: hostvars[inventory_hostname]
      register: hostvars_ansible_rhel
      delegate_to: ansible_rhel

    - name: Simple printing of recorded variables 
      debug:
        msg: "{{ item }}"
      loop:
        - "{{ hostvars_localhost }}"
        - "{{ hostvars_ansible_rhel }}"
            
    - name: If localhost = ansible_rhel, take action 
      debug:
        msg: "Two hosts match --> Take action"
      when: "{{ hostvars_localhost == hostvars_ansible_rhel }}" 