- name: Discover if two json inputs are different, and take action accordingly
  hosts: localhost
  vars:
    - localhost_facts: "{{ ansible_facts }}"
    - json_homie: "{{ 'homie' | to_json }}"
    - json_tate: "{{ 'tate' | to_json }}"
    - json_homieII: "{{ 'homie' | to_json }}"

  tasks:
    - name: Simple facts print statement 
      debug:
        msg: "{{ localhost_facts }}"
            
    - name: If localhost facts include tate, take action 
      debug:
        msg: "Two inputs match --> Take action"
      when: json_tate in localhost_facts

    - name: If 'homie' == 'tate' in json, take action 
      debug:
        msg: "Two inputs match --> Take action"
      when: json_homie == json_tate

    - name: If 'homie' != 'tate' in json, take action 
      debug:
        msg: "Two inputs DO NOT match --> take action"
      when: json_homie != json_tate

    - name: If 'homie' == 'homie' in json, take action 
      debug:
        msg: "Two inputs match --> take action"
      when: json_homie == json_homieII 