# Tate DeVito
# 
# References: 
# https://stackoverflow.com/questions/59949438/compare-ansible-registered-variables-for-multiple-hosts

- name: Discover if two json inputs are different, and take action accordingly
  hosts: 
    - localhost
  gather_facts: no

  tasks:
    - name: Record facts in localhost as a variable 
      debug:
        var: hostvars[inventory_hostname]
      register: hostvars_localhost
      delegate_to: localhost

    - name: Simple printing of the hostvars_localhost registered variable 
      debug:
        msg: "{{ hostvars_localhost }}"
            
    - name: If x = xII, take action 
      vars: 
        - x: x
        - xII: x
      debug:
        msg: "Two inputs match --> Take action"
      when: x == xII 